### ISSUE TITLE
Analysis center not mandatory in schema

### ISSUE THREAD

**Issue by pabarcgar** [enasequence/schema#1]
Hello

I submitted some days ago to ENA an Analysis XML that validated again the XSD schema with no error. However, webin replied that the analysis was incorrect because it was missing center name:
                                                                        
    ERROR: In analysis, alias:"XXXX", accession:"ERZ491433".    
    Missing center name.                   

The analysis center attribute is optional in SRA.analysis.xsd:
https://github.com/enasequence/schema/blob/master/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.analysis.xsd#L320

Can "analysis_center" be made mandatory in the XSD file? Or is there any case when that center is not mandatory?

Thanks,
Pablo

**Comment by pabarcgar** [comment]
It may be that the error is related with the attribute "center_name" and not with "analysis_center". This attribute is also not mandatory in the XSD (it seems to be defined in SRA.common.xsd schema), so there is still an issue:

https://github.com/enasequence/schema/blob/master/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.common.xsd#L17

**Comment by raskoleinonen** [comment]
Hi Pablo,

The center_name should be optional for non-broker submitters and should be automatically filled by the Webin submission service.

Brokers are required to provide a center name.

Could I first please ask you to confirm the Webin submission account or e-mail address you used when submitting the Analysis XML?

If the account is a non-broker account we should investigate further. In this case, it might help us if you could provide an example of a problematic Analysis XML.

Best,
Rasko

**Comment by pabarcgar** [comment]
Hi Rasko

I used the EVA account, that I think is a broker one, so that should explain that. I'm closing this ticket then, because there is no bug.

Thanks,
Pablo
