### ISSUE TITLE
'Target sequencing' experiment type needed in SRA.analysis.xsd

### ISSUE THREAD

**Issue by BaronKoy** [enasequence/schema#12]
Please can we have 'Target sequencing' added to the list of valid experiment types at:

https://github.com/enasequence/schema/blob/7e85ab42df86c64467e524d7d7b42ff250671faf/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.analysis.xsd#L195-L214

**Comment by raskoleinonen** [comment]
Added request to backlog.

**Comment by raskoleinonen** [comment]
Change has been deployed into production.
