### ISSUE TITLE
Add "28S rRNA" as locus_name enumeration in SRA.experiment.xsd

### ISSUE THREAD

**Issue by ikostadi** [enasequence/schema#13]
Dear ENA Team,

could you please add the large eukaryotic subunit to the enumerqation list for locus_name, similar to this:
https://github.com/enasequence/schema/blob/7fbf0178fca943544ea3739b12250961835a230a/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.experiment.xsd#L562-L568

https://en.wikipedia.org/wiki/28S_ribosomal_RNA

Many thanks!

**Comment by ikostadi** [comment]
Dear ENA Team,

is there a chance to get this added to the schema any time soon?

Best,
Ivo

**Comment by raskoleinonen** [comment]
Ok, lets do this now.

**Comment by ikostadi** [comment]
Great, thanks!

**Comment by raskoleinonen** [comment]
28S rRNA support has been added to Webin REST service:
https://www.ebi.ac.uk/ena/submit/drop-box/submit

Interactive submission support will be added later today or tomorrow.

**Comment by raskoleinonen** [comment]
Now supported by interactive Webin as well.

**Comment by ikostadi** [comment]
Better late than never, thank you very much @raskoleinonen !

**Comment by ikostadi** [comment]
> Better late than never, thank you very much @raskoleinonen !

I meant I was (very late) saying "thanks" :)
