### ISSUE TITLE
'Target sequencing' experiment type needed in SRA.analysis.xsd

### ISSUE THREAD

**Issue by BaronKoy** [enasequence/schema#14]
Are we able to add 'Target sequencing' to the list of valid experiment types? There seems to be a number of individuals requesting if they can use this as an option during EVA submission: 

https://github.com/enasequence/schema/blob/7e85ab42df86c64467e524d7d7b42ff250671faf/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.analysis.xsd#L195-L214

**Comment by raskoleinonen** [comment]
Ok, we will do this later this week or next week.

**Comment by josuemv** [comment]
Dear Baron "SEQUENCE_VARIATION" already supports "Target sequencing" EXPERIMENT_TYPE:

https://github.com/enasequence/schema/blob/6fcf22608fa1e1764a5cc01a8c516063239120f1/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.analysis.xsd#L195-L220

**Comment by raskoleinonen** [comment]
Ok, "Target sequencing" has already been added. I am closing this ticket as resolved.
