### ISSUE TITLE
Add support for CSI index files in analysis schema

### ISSUE THREAD

**Issue by malloryfreeberg** [enasequence/schema#18]
Hello,

I am trying to submit BCF + CSI index files as part of an analysis to EGA, which uses the SRA.analysis.xsd ENA schema. I noticed that, although I can set `filetype="bcf"` for my BCF files, I cannot set `filetype="csi"` for my CSI index files as "csi" is not one of the valid values in the CV of the schema for the attribute `filetype`. 

CSI is now the default index over TBI/tabix for VCF and BCF files in `htslib`, as reflected in tools like `bcftools`:

```bash
$ bcftools index

About:   Index bgzip compressed VCF/BCF files for random access.
Usage:   bcftools index [options] <in.bcf>|<in.vcf.gz>

Indexing options:
    -c, --csi                generate CSI-format index for VCF/BCF files [default]
...
    -t, --tbi                generate TBI-format index for VCF files
...
```

and `samtools`:

```bash
$ samtools index
Usage: samtools index [-bc] [-m INT] <in.bam> [out.index]
Options:
  -b       Generate BAI-format index for BAM files [default]
  -c       Generate CSI-format index for BAM files
...
```

Can I please request that "csi" be added as a valid value for the `filetype` attribute in the [SRA.analysis.xsd](https://github.com/enasequence/schema/blob/master/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.analysis.xsd) schema? Thank you!

**Comment by raskoleinonen** [comment]
Hi Mallory,

Could you please confirm the analysis type you would use for the BCF + CSI index files?

**Comment by malloryfreeberg** [comment]
Hi @raskoleinonen ,

The type would be the same as those for VCF + TBI index files, `SEQUENCE_VARIATION`.

**Comment by raskoleinonen** [comment]
Currently permitted file groups for SEQUENCE_VARIATION:

- vcf, tabix, readme_file, other
- vcf_aggregate, tabix, readme_file, other  

Suggested additional permitted file groups for SEQUENCE_VARIATION:

- bcf, tabix, readme_file, other
- bcf, csi, readme_file, other
- bcf_aggregate, tabix, readme_file, other  
- bcf_aggregate, csi, readme_file, other  

Questions:
- Do we need bcf_aggregate? vcf_aggregate has been used for 134 files while vcf has been used for 41791 files.

Notes:
- tabix (tbi) is only supported for VCF files while csi is supported for both VCF and BCF files
- csi would be a new file format
- bcf_aggregate would be a new file format




-

**Comment by malloryfreeberg** [comment]
Thanks for reviewing, @raskoleinonen.

I agree that currently tabix/tbi is *not* supported for BCF. Therefore, I suggest these additional permitted file groups for SEQUENCE_VARIATION:
- bcf, csi, readme_file, other
- bcf_aggregate, csi, readme_file, other
- vcf, csi, readme_file, other
- vcf_aggregate, csi, readme_file, other

Regarding the question about bcf_aggregate, I'm not sure if there is a use case for bcf_aggregate, as I haven't been able to find anything about this file type online. Perhaps @tcezard might have more insight into this.

**Comment by raskoleinonen** [comment]
The change has been deployed into production.

**Comment by malloryfreeberg** [comment]
Thank you @raskoleinonen and team!
