### ISSUE TITLE
EGA DAC Schema - Mandatory DAC Title

### ISSUE THREAD

**Issue by M-casado** [enasequence/schema#21]
Hello, EGA would like to request a change in the Data Access Committee (DAC) metadata schemas: **make DAC's Title mandatory**. As it is currently several DACs are submitted lacking their title, which leads to incomplete information and the need for HelpDesk to fill it. 

For what I have seen, I believe the change could be as simple as going from:
````
<xs:element name="TITLE" type="xs:string" minOccurs="0" maxOccurs="1">
````
To:
````
<xs:element name="TITLE" type="xs:string" minOccurs="1" maxOccurs="1">
````
It is already mandatory at our Submitter Portal, and we believe it should be the same in Webin. 

Thank you in advance!

**Comment by raskoleinonen** [comment]
TITLE is now mandatory as requested.
