### ISSUE TITLE
NOMe-seq and other bisulfite approaches, library strategy

### ISSUE THREAD

**Issue by karl616** [enasequence/schema#3]
Hi,
I cannot find specialized bisulfite approaches like NOMe-seq, TAB-seq etc. among the library strategies:

https://github.com/enasequence/schema/blob/7ca44d9502d339ed07bda7961f172a3ea51a257c/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.experiment.xsd#L123

Would it be correct to submit such assays as Bisulfite sequencing? I guess it comes down to how fine grained you want this to be?

I know EGA hosts NOMe data under this entry:
EGAD00001002735
but I don't have access to the metadata. I could only find ways to access the study.

**Comment by raskoleinonen** [comment]
Dear Karl Nordström,

Yes, it would be best to submit such assays using the "Bisulfite-Seq" library strategy as you suggested.

Best Regards,
Rasko Leinonen
