### ISSUE TITLE
Is assembly.xsd still used?

### ISSUE THREAD

**Issue by froggleston** [enasequence/schema#6]
Hi there,

From the latest documentation it looks like assemblies are represented in the analysis.xsd, and not the assembly.xsd. There also doesn't seem to be a way to reference the assembly types in analysis.xsd so I presume that assembly.xsd is no longer used. Is this the case?

Cheers

Rob

**Comment by raskoleinonen** [comment]
Hi Rob,

assembly.xsd continues to be used as part of assembly presentation, for example:

https://www.ebi.ac.uk/ena/data/view/GCA_000753055.1&display=xml

analysis.xsd is used when submitting genome assemblies to ENA.

Best,
Rasko

**Comment by froggleston** [comment]
Hi Rasko,

Great - thanks for the clarification!

Cheers

Rob
