### ISSUE TITLE
'Whole transcriptome sequencing' experiment type needed in SRA.analysis.xsd

### ISSUE THREAD

**Issue by BaronKoy** [enasequence/schema#8]
Please can we have 'Whole transcriptome sequencing' added to the list of valid experiment types at:

https://github.com/enasequence/schema/blob/7e85ab42df86c64467e524d7d7b42ff250671faf/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.analysis.xsd#L195-L214

**Comment by raskoleinonen** [comment]
Sure. Being very easy to do I have added this to the top of our product backlog. Next sprint planning meeting will be on Tuesday 25th and the ticket will be get picked up then.
